name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Run linting
      run: |
        flake8 src/ --max-line-length=120

    - name: Run tests
      run: pytest --cov --cov-branch --cov-report=xml
      
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}